### ISSUE TITLE
Create a new AttestationAuthority CRD with a controoler.

### ISSUE THREAD

**Issue by tejal29** [grafeas/kritis#13]
The AttestationAuthority CRD will look like:
Definition
```
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
    name: attestation-authority
spec:
  group: kritis.github.com
  version: v1beta1
  scope: Namespaced
  names:
    plural: attestationauthorities
    singular: attestationauthority
    kind: AttestationAuthority
```
Fields.
```
apiVersion: kritis.github.com/v1beta1
kind: AttestationAuthority
metadata:
    name: qa-attestator
    namespace: qa 
spec:
    noteReference: v1alpha1/projects/image-signing
    privateKeySecretName: foo
    publicKeyData: dsfdasfdkla
```

The Controller will if kubernetes secret "foo" exists in namespace "qa".

TODO: What Controller can do if secret does not exist?. 
1. The Controller can instead create gpg secrets and update the CRD with the public key?
