### ISSUE TITLE
No support for the separation of GCR and Attestor into different GCP projects

### ISSUE THREAD

**Issue by marco-lancini** [grafeas/kritis#396]
## Expected Behavior

It would be expected that Kritis would respect the value of `noteReference` spec of a `AttestationAuthority` both when creating and fetching attestations.

## Actual Behavior

Although when creating attestations it respects the `noteReference` value [1], when listing attestations kritis uses the project in which the GCR lives, by extracting it directly from the image name [2].
This prevent the case of having GCR and the Attestor living in 2 different GCP projects.

[1] https://github.com/grafeas/kritis/blob/bc811c62913cdc0b95ce59949084dad42d6c9e4e/pkg/kritis/metadata/containeranalysis/containeranalysis.go#L149
[2] https://github.com/grafeas/kritis/blob/bc811c62913cdc0b95ce59949084dad42d6c9e4e/pkg/kritis/metadata/containeranalysis/containeranalysis.go#L102 

## Steps to Reproduce the Problem

1. Install and run Kritis as explained in the [installation guide](https://github.com/grafeas/kritis/blob/master/docs/install.md)
2. The projects used are:
    A. `project-gcr`: hosting GCR
    B. `project-attestor`: hosting the attestor
3. Create an attestation authority (note the `noteReference: v1beta1/projects/project-attestor`)
```
---
apiVersion: v1
kind: List
items:
  - apiVersion: kritis.grafeas.io/v1beta1
    kind: GenericAttestationPolicy
    metadata:
      name: my-gap
      namespace: default
      labels:
        kritis.grafeas.io/install: ''
    spec:
      attestationAuthorityNames:
        - kritis-authority
  - apiVersion: kritis.grafeas.io/v1beta1
    kind: AttestationAuthority
    metadata:
      name: kritis-authority
      namespace: default
    spec:
      noteReference: v1beta1/projects/project-attestor
      privateKeySecretName: gcp-attestations-pgp
      publicKeyData: /secret/gpg.pub
      volumeMounts:
        - name: gcp-attestations-pgp
          mountPath: /secret
      volumes:
        - name: gcp-attestations-pgp
          secret:
            secretName: gcp-attestations-pgp
```

4. Try to deploy an image which has attestations and should be allowed (note `project-gcr` used in `image`):
```
cat <<EOF | kubectl apply -f -
apiVersion: v1
kind: Pod
metadata:
  name: test-alpine
spec:
  containers:
    - name: test-alpine
      image: eu.gcr.io/project-gcr/library/alpine@sha256:<sha>
EOF
```
5. Obtain an error, since Kritis is trying to fetch attestations from the wrong GCP project
```
E0830 15:40:18.564629 1 review.go:143] Error while fetching attestations rpc error: code = PermissionDenied desc = permission "containeranalysis.occurrences.list" denied for project "project-gcr", entity ID ""
```
